name: Main Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t my-image .
        docker push my-image

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.mailgun.org
        server_port: 465
        username: ${{ secrets.MAILGUN_USERNAME }}
        password: ${{ secrets.MAILGUN_PASSWORD }}
        subject: GitHub Actions job result
        to: github-actions-8ce6454@unknwon.io
        from: GitHub Actions (jchwl0527/gogs)
        reply_to: noreply@unknwon.io
        body: The job "buildx" of https://github.com/jchwl0527/gogs/commit/${{ github.sha }} completed with "${{ job.status }}".
